(function(){
var QR='111111100100111001111001001111111,100000100100011101001010001000001,101110101010110001100000001011101,101110101011001110001110001011101,101110101101100100100100101011101,100000101001011110001100001000001,111111101010101010101010101111111,000000001001000100100110100000000,101111100111101111101010101111100,111010010010100000010101000000011,110001110000100100101100010010100,111111011111001000000111101100100,110110100011100100110100100011000,110111011011001110001110011100011,101010101100000001010111100000110,000011001111110010111111001100100,000011101111000011111001000011000,001101011000000001010011111101111,000100111101000101000010010001100,010110000010011001110001100000100,100100111001101110001110110111001,111110010011111100100000101000011,100001110110100111101100110001100,101100010101011100100111110100101,100110101010110111101000111111001,000000001101101000010110100010111,111111100010011100101100101010100,100000101100110100001111100010111,101110101001000100100100111111000,101110101101001110001111010011101,101110101110111001010100100100000,100000100110100010111101010001100,111111101101000011111000101100110'.split(',');
(function(){var n=QR.length,d='';QR.forEach(function(r,y){for(var x=0;x<n;){if(r[x]==='1'){var s=x;while(x<n&&r[x]==='1')x++;d+='M'+s+' '+y+'h'+(x-s)+'v1h-'+(x-s)+'z'}else x++}});var q=document.getElementById('qr');q.setAttribute('viewBox','-2 -2 '+(n+4)+' '+(n+4));q.innerHTML='<rect x="-2" y="-2" width="'+(n+4)+'" height="'+(n+4)+'" fill="#fff"/><path d="'+d+'" fill="#111"/>'})();
var T={
 en:{"nav.project":"Project","nav.opus":"Opus watch","nav.about":"About","nav.coffee":"Coffee","hero.badge":"Open to collab","hero.pill":"Python · AI tooling · Automation","hero.title":"Bridges for <em>AI coding</em> tools","hero.lead":"I'm yumi, a Python coder. I build relays and key managers that let different AI stations work inside the editor you actually use.","cta.clodkey":"ClodKey on GitHub","cta.coffee":"Buy me a coffee","p.eyebrow":"Main project","p.title":"ClodKey — one key, any editor","p.sub":"Some API stations accept requests only in the Claude CLI format. ClodKey's Zoo Bridge translates that format, so the same key works as a regular provider in Zoo Code / Roo Code.","p.f1":"Tray key manager for Claude CLI — no installer, no console windows","p.f2":"Profiles with a locked System default, one-click apply","p.f3":"Keys encrypted with Windows DPAPI","p.f4":"Built-in model check — see what the station serves right now","p.f5":"Light / dark, English by default · ru · zh · es","p.open":"Open repository","p.diag":"request → translate → response","p.tested":"tested","p.tested2":"tested via bridge","p.others":"Other coding tools","p.untested":"not tested","o.eyebrow":"Opus watch","o.title":"Know when Opus goes live","o.sub":"agentrouter.org turns the Claude Opus family on and off on a schedule. ClodKey's model check (⟳) shows what the station serves right now — no more requests burned on a model that is off.","a.eyebrow":"About","a.title":"From scripts to bridges","a.sub":"I like tools that start with one click and don't trust magic without logs.","a.s1":"Scripts","a.s1p":"Excel reports, parsing, killing routine.","a.s2":"Telegram bots","a.s2p":"Small services people use every day.","a.s3":"Services","a.s3p":"Databases, Docker, deploys.","a.s4":"AI bridges","a.s4p":"Relays and key managers for AI coding tools.","c.eyebrow":"Support","c.title":"Fuel the next bridge","c.sub":"If ClodKey saved you time, a coffee keeps the next tool coming. Every cup fills the meter.","m.title":"Buy me a coffee","m.copy":"Copy","m.copied":"Copied","m.warn":"Ethereum (ERC20) only. Other networks = lost funds.","m.thanks":"Say thanks ↗","toast":"Address copied — thank you!"},
 ru:{"nav.project":"Проект","nav.opus":"Opus","nav.about":"Обо мне","nav.coffee":"Кофе","hero.badge":"Открыт к сотрудничеству","hero.pill":"Python · AI-инструменты · Автоматизация","hero.title":"Мосты для <em>AI-инструментов</em> разработки","hero.lead":"Я yumi, Python-кодер. Делаю ретрансляторы и менеджеры ключей, чтобы разные AI-станции работали в том редакторе, которым вы пользуетесь.","cta.clodkey":"ClodKey на GitHub","cta.coffee":"Угостить кофе","p.eyebrow":"Главный проект","p.title":"ClodKey — один ключ, любой редактор","p.sub":"Некоторые API-станции принимают запросы только в формате Claude CLI. Zoo Bridge в ClodKey переводит этот формат — и тот же ключ работает как обычный провайдер в Zoo Code / Roo Code.","p.f1":"Менеджер ключей Claude CLI в трее — без установки и консольных окон","p.f2":"Профили с защищённым системным, применение в один клик","p.f3":"Ключи зашифрованы Windows DPAPI","p.f4":"Проверка моделей — видно, что станция отдаёт прямо сейчас","p.f5":"Светлая / тёмная тема, английский по умолчанию · ru · zh · es","p.open":"Открыть репозиторий","p.diag":"запрос → перевод → ответ","p.tested":"проверено","p.tested2":"проверено через мост","p.others":"Другие инструменты","p.untested":"не проверялось","o.eyebrow":"Слежение за Opus","o.title":"Узнай, когда включили Opus","o.sub":"agentrouter.org включает и выключает семейство Claude Opus по расписанию. Проверка моделей в ClodKey (⟳) показывает, что станция отдаёт сейчас, — запросы в выключенную модель больше не сгорают.","a.eyebrow":"Обо мне","a.title":"От скриптов к мостам","a.sub":"Люблю инструменты, которые запускаются в один клик, и не доверяю магии без логов.","a.s1":"Скрипты","a.s1p":"Отчёты Excel, парсинг, борьба с рутиной.","a.s2":"Telegram-боты","a.s2p":"Небольшие сервисы на каждый день.","a.s3":"Сервисы","a.s3p":"Базы данных, Docker, деплой.","a.s4":"AI-мосты","a.s4p":"Ретрансляторы и менеджеры ключей для AI-инструментов.","c.eyebrow":"Поддержка","c.title":"Заправь следующий мост","c.sub":"Если ClodKey сэкономил тебе время — чашка кофе приближает следующий инструмент.","m.title":"Угостить кофе","m.copy":"Копир.","m.copied":"Готово","m.warn":"Только Ethereum (ERC20). Другие сети = потеря средств.","m.thanks":"Сказать спасибо ↗","toast":"Адрес скопирован — спасибо!"},
 es:{"nav.project":"Proyecto","nav.opus":"Opus","nav.about":"Sobre mí","nav.coffee":"Café","hero.badge":"Abierto a colaborar","hero.pill":"Python · Herramientas IA · Automatización","hero.title":"Puentes para herramientas de <em>código con IA</em>","hero.lead":"Soy yumi, programador Python. Construyo relés y gestores de claves para que distintas estaciones de IA funcionen en el editor que realmente usas.","cta.clodkey":"ClodKey en GitHub","cta.coffee":"Invítame un café","p.eyebrow":"Proyecto principal","p.title":"ClodKey — una clave, cualquier editor","p.sub":"Algunas estaciones API solo aceptan el formato de Claude CLI. Zoo Bridge de ClodKey traduce ese formato y la misma clave funciona como proveedor normal en Zoo Code / Roo Code.","p.f1":"Gestor de claves de Claude CLI en la bandeja — sin instalador ni consolas","p.f2":"Perfiles con System bloqueado por defecto, aplicar en un clic","p.f3":"Claves cifradas con Windows DPAPI","p.f4":"Comprobación de modelos — qué sirve la estación ahora mismo","p.f5":"Claro / oscuro, inglés por defecto · ru · zh · es","p.open":"Abrir repositorio","p.diag":"petición → traducción → respuesta","p.tested":"probado","p.tested2":"probado vía puente","p.others":"Otras herramientas","p.untested":"sin probar","o.eyebrow":"Vigilancia de Opus","o.title":"Sabe cuándo se activa Opus","o.sub":"agentrouter.org activa y desactiva la familia Claude Opus según un horario. La comprobación de modelos de ClodKey (⟳) muestra lo que sirve la estación ahora mismo.","a.eyebrow":"Sobre mí","a.title":"De scripts a puentes","a.sub":"Me gustan las herramientas que arrancan con un clic y no confío en la magia sin logs.","a.s1":"Scripts","a.s1p":"Informes Excel, parsing, adiós a la rutina.","a.s2":"Bots de Telegram","a.s2p":"Pequeños servicios de uso diario.","a.s3":"Servicios","a.s3p":"Bases de datos, Docker, despliegues.","a.s4":"Puentes IA","a.s4p":"Relés y gestores de claves para herramientas de IA.","c.eyebrow":"Apoyo","c.title":"Alimenta el próximo puente","c.sub":"Si ClodKey te ahorró tiempo, un café acerca la próxima herramienta.","m.title":"Invítame un café","m.copy":"Copiar","m.copied":"Copiado","m.warn":"Solo Ethereum (ERC20). Otras redes = fondos perdidos.","m.thanks":"Dar las gracias ↗","toast":"Dirección copiada — ¡gracias!"}
};
var typedLines=['$ clodkey apply --profile system','$ bridge start :33110','$ check models → opus: live'];
var reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
var lang=new URLSearchParams(location.search).get('lang')||localStorage.getItem('lang')||'en';
if(!T[lang])lang='en';
function t(k){return T[lang][k]!=null?T[lang][k]:T.en[k]}
function splitH1(){var h=document.getElementById('h1'),tmp=document.createElement('div'),out='',i=0;tmp.innerHTML=t('hero.title');tmp.childNodes.forEach(function(n){var em=n.nodeType===1;n.textContent.split(/(\s+)/).forEach(function(w){if(!w)return;if(/^\s+$/.test(w)){out+=' ';return}var s='<span class="w"><span style="transition-delay:'+(0.08*i++)+'s">'+w+'</span></span>';out+=em?'<em>'+s+'</em>':s})});h.innerHTML=out}
function apply(){document.documentElement.lang=lang;document.querySelectorAll('[data-i]').forEach(function(el){var v=t(el.getAttribute('data-i'));if(typeof v==='string')el.innerHTML=v});splitH1();document.querySelectorAll('#lang button').forEach(function(b){b.classList.toggle('on',b.dataset.l===lang)})}
function ready(){document.body.classList.add('ready')}
document.querySelectorAll('#lang button').forEach(function(b){b.onclick=function(){lang=b.dataset.l;localStorage.setItem('lang',lang);document.body.classList.remove('ready');apply();requestAnimationFrame(function(){requestAnimationFrame(ready)})}});
apply();requestAnimationFrame(function(){setTimeout(ready,60)});addEventListener('load',ready);
var li=0,ci=0,del=false,ty=document.getElementById('typed');
function tick(){var s=typedLines[li];if(reduce){ty.textContent=s;return}if(!del){ci++;if(ci>s.length){del=true;return setTimeout(tick,1600)}}else{ci--;if(ci<0){del=false;ci=0;li=(li+1)%typedLines.length}}ty.textContent=s.slice(0,ci);setTimeout(tick,del?22:48)}tick();
if('IntersectionObserver' in window){var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}})},{threshold:.15});document.querySelectorAll('.reveal').forEach(function(el){io.observe(el)})}else document.querySelectorAll('.reveal').forEach(function(el){el.classList.add('in')});
var nav=document.getElementById('nav'),prog=document.getElementById('prog');
addEventListener('scroll',function(){var y=scrollY,h=document.documentElement.scrollHeight-innerHeight;nav.classList.toggle('scrolled',y>8);prog.style.width=(h>0?y/h*100:0)+'%'},{passive:true});
document.querySelectorAll('.spot').forEach(function(c){c.addEventListener('pointermove',function(e){var r=c.getBoundingClientRect();c.style.setProperty('--mx',(e.clientX-r.left)+'px');c.style.setProperty('--my',(e.clientY-r.top)+'px')})});
if(!reduce&&matchMedia('(pointer:fine)').matches)document.querySelectorAll('.mag').forEach(function(b){b.addEventListener('pointermove',function(e){var r=b.getBoundingClientRect();b.style.transform='translate('+((e.clientX-r.left-r.width/2)*.18)+'px,'+((e.clientY-r.top-r.height/2)*.28)+'px)'});b.addEventListener('pointerleave',function(){b.style.transform=''})});
var st=document.getElementById('opusSt'),row=document.getElementById('opusRow'),fo=document.getElementById('floatOpus'),clk=document.getElementById('clk'),on=false;
function z(n){return(n<10?'0':'')+n}
setInterval(function(){var d=new Date();clk.textContent=z(d.getHours())+':'+z(d.getMinutes())+':'+z(d.getSeconds())},1000);
setInterval(function(){on=!on;st.textContent=on?'OK':'off';st.className='st '+(on?'on':'off');fo.textContent=on?'live':'off';row.classList.add('flash');setTimeout(function(){row.classList.remove('flash')},600)},3200);
var ov=document.getElementById('ov'),last=null;
function open(){last=document.activeElement;ov.classList.add('open');ov.setAttribute('aria-hidden','false');setTimeout(function(){document.getElementById('x').focus()},50)}
function close(){ov.classList.remove('open');ov.setAttribute('aria-hidden','true');if(last&&last.focus)last.focus()}
document.querySelectorAll('[data-coffee]').forEach(function(b){b.addEventListener('click',open)});
document.getElementById('x').onclick=close;
ov.addEventListener('click',function(e){if(e.target===ov)close()});
addEventListener('keydown',function(e){if(e.key==='Escape'&&ov.classList.contains('open'))close()});
if(location.hash==='#donate')open();
var cups=+(localStorage.getItem('cups')||0);
function meter(){document.querySelectorAll('#meter i').forEach(function(m,i){m.classList.toggle('on',i<cups)})}meter();
var toast=document.getElementById('toast');
function showToast(s){toast.textContent=s;toast.classList.add('show');setTimeout(function(){toast.classList.remove('show')},2200)}
document.getElementById('copy').onclick=function(){var a=document.getElementById('addr').textContent,b=this;
function ok(){b.textContent=t('m.copied');b.classList.add('done');showToast(t('toast'));cups=Math.min(5,cups+1);localStorage.setItem('cups',cups);meter();setTimeout(function(){b.textContent=t('m.copy');b.classList.remove('done')},1800)}
function fallback(){var r=document.createRange();r.selectNodeContents(document.getElementById('addr'));var s=getSelection();s.removeAllRanges();s.addRange(r);try{document.execCommand('copy');ok()}catch(e){}}
if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(a).then(ok,fallback);else fallback()};
document.getElementById('yr').textContent=new Date().getFullYear();
})();
